FROM bitnami/python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY kafka_producer /app

# Install netcat
RUN apt-get update && apt-get install -y netcat-traditional

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]