FROM bitnami/python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY kafka_producer /app

RUN apt-get update && apt-get install -y netcat-traditional


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


ENTRYPOINT ["/entrypoint.sh"]